### ISSUE TITLE
eer_threshold doesn't behave as expected

### ISSUE THREAD

**Issue by siebenkopf** [bioidiap/bob.measure#3]
Hi there,

I have found out that the ``eer_threshold`` function (as well as the ``min_hter_threshold`` function) does not perform as expected in case of highly unbalanced scores. Particularly, when I try to use a special low valued error indicator such as `-10000`, the returned threshold is garbage. Consider the following example:

```
positives = [1.]*100 + [-10000.]
negatives = [-1.]*100 + [-10000.]

threshold = bob.measure.eer_threshold(negatives, positives)
print threshold, bob.measure.farfrr(negatives, positives, threshold)
print 0, bob.measure.farfrr(negatives, positives, 0)
```

The outputs of the two print commands are:

```
-4999.5 (0.9900990099009901, 0.009900990099009901)
0 (0.0, 0.009900990099009901)
```
So, the second output, where I estimated a threshold ``0`` myself, is much more suitable than the first output, which was generated by ``eer_threshold`` (the ``min_hter_threshold`` behaves exactly the same).

I would suggest, we should rethink our implementation of the thresholds. I am pretty sure that there exist smarter ways (I had implemented some during my PhD...)

Cheers
Manuel

**Comment by anjos** [comment]
Sure. I'd suggest we setup a few test cases (if not already there), before moving to a new method, to guarantee we'll get similar results throughout this move. We have too many papers already published using the current technique.

**Comment by siebenkopf** [comment]
I have re-implemented the threshold computation. It seems to get the same results as before, at least when computing the EER or HTER on the development set. 
In the old version, **any** threshold that would give the expected EER / min_HTER was accepted (the calculation was repeatable, but the real threshold had no theoretical foundation), while now the threshold is based on the best separation between positives and negatives. However, as the thresholds change slightly, it happens that the HTER on the evaluation set might change, and so does the EPC curve, especially for the extremes of weights 0 and 1 for the FAR.

@anjos: As you said, we have published quite some papers with the old evaluation technique. Obviously, we should give the possibility to generate the exact values, but this should be possible based on the version. As soon as it compiles and it is getting tested over night, I will push a new minor version (2.1.0) including the fix. What do you think about that approach?

**Comment by anjos** [comment]
@siebenkopf: one question from Seb et al: have you tested this implementation against your stock baselines and verified similar results are achieved?

**Comment by siebenkopf** [comment]
Good point. Indeed, now I have checked the baseline results of ``bob.bio.face`` on the AT&T database (for which we have only a dev set). I have evaluated them with the old and the new version of the thresholds, and the results are identical, using both the eer_threshold and the min_hter_threshold (except for a small difference in the EER of the PLDA algorithm, which varies from old:10.789% to new: 10.816%), which might be due to the fact that identical scores might be handled differently during threshold calculation between the versions. 
However, I didn't test the evaluation set (i.e., compute the threshold on the dev set and use it on the eval set) since I don't have access to such databases here. I assume that the results might differ slightly, as the actual values of the thresholds changed.

Anyways, I have run the old nose tests, and all of them pass. I just had to modify the EPC curve, the reason is the same that we have discussed before. I believe that the new thresholds for EPC at the extremes ``w=0`` and ``w=1`` are more appropriate.

@smarcel: Do you want me to also run experiments on databases with an eval set? I would need to do that on an Idiap machine...

**Comment by smarcel** [comment]
Yes I would prefer to have a test with a larger experiment with a dev and test set.

Don't you still have an access to Idiap machines ? Normally your account was extended so your credentials are still valid -- feel free to use Idiap machines for that.

cheers

**Comment by siebenkopf** [comment]
Indeed, I still have access to the Idiap machines. However, I realized that I actually don't need to re-run experiments, but I can simply use some precalculated scores... I will take the ones from the BTFS paper (on MOBIO). There, it seems that we have a variety of algorithms/scores to be tested. I'll keep you posted on the results.

**Comment by smarcel** [comment]
from the scores indeed ! thanks for checking 

hope all is good in UCCS 

cheers

**Comment by siebenkopf** [comment]
OK, so I have run the evaluation on the male face scores of several systems. The good news is that, when I use the EER as minimization criterion, the results on the DEV set are identical, while the results on the EVAL set are almost identical, there is only one negligible difference in the CPqD scores of the HTER on EVAL:
```
CPqD: old 7.668% -- new 7.669%
```

On the other hand, the when using the HTER as minimization criterion, the threshold differs more and, thus, the results. There, we already have some systems (4 out of 9), where the results on the DEV set already differs slightly (the first value is the old, the second the new evaluation):
```
baseline:   14.702% -- 14.697%
CPqD:        5.367% --  5.365%
GRADIANT:    3.126% --  3.125%
TUT:         5.468% --  5.462%
```
Now, when evaluating the EVAL set (using the min-HTER threshold from DEV set), we start getting higher differences (note that we have one more system with differences):
```
baseline:  17.301% -- 17.273%
CPqD:       7.646% --  7.605%
GRADIANT:   9.477% --  9.491%
TUT:       10.083% -- 10.035%
UNILJ-ALP:  7.685% --  7.433%
```
It appears that most of the systems get better results with the new evaluation (both on the DEV and on the EVAL set), which IMHO means that the new threshold is working better than the old one.

I can investigate more, why these differences in the HTER (especially on the DEV set) exists, but I can clearly see that the old way of minimizing HTER in some cases **did not actually minimize** the HTER, but only found a threshold that is **close** to the minimum. I assume that the same is true for the EER, but in my experiments I didn't see any changes in the EER (at least on the DEV set).

Anyways, the results on the EVAL set are relatively close to the ones from the old evaluation. What do you think, should we start using the new way?

**Comment by siebenkopf** [comment]
I have one more concern with the implementation details. So far, I am copying the scores as my method needs sorted scores, and the input ``blitz::Array``'s are ``const``. Do you think it is a good idea to provide a non-const ``blitz::Array`` to the function, so that I can sort the scores in place? This would have an impact on the ``numpy.array``'s on the python side as well...

Of course, I'll add proper documentation that will clarify this fact...

**Comment by smarcel** [comment]
Hi Manuel

thank you for the nice comparison. You have a convincing demonstration. I agree to start using the new way. Please commit the change.

When this will be done could you just do a post on the google-group to inform people about that fix so they can decide or not to re-run their previous experiments.

**Comment by siebenkopf** [comment]
I have tried to implement the sorting using the ``blitz::Array``'s directly, but it seems that blitz does not support sorting (at least not using the iterators). When I try:
```
blitz::Array<double,1> scores(...);
std::sort(scores.begin(), scores.end(), std::less<double>());
```
I get the compiler error:
```
...
/usr/include/c++/4.8/bits/stl_algo.h:5499:22: error: no match for ‘operator-’ (operand types are ‘blitz::ArrayIterator<double, 1>’ and ‘blitz::ArrayIterator<double, 1>’)
     std::__lg(__last - __first) * 2, __comp);
```

Has anyone yet tried to sort arrays using blitz++? Any other advice?

**Comment by anjos** [comment]
@siebenkopf: I'm not sure it is good idea to change the input object on a function. Copying sounds like the safe solution.

**Comment by anjos** [comment]
One possible (conservative) way through this would be:

1. Add a flag `sorted=False`, which would imply in the copying
2. Allow the user to sort the scores and pass `sorted=True`, which avoids the copying.

**Comment by tiagofrepereira2012** [comment]
Hey Manuel (@siebenkopf),

We will update all the bob packages because of this commit (928335ae44b658215849fe234a4e556414077f3c).

Shall we tag this package as 2.1.0 ?

Thanks and cheers

**Comment by tiagofrepereira2012** [comment]
Hey Manuel (@siebenkopf),

We need to do a major update in the bob packages (including this one).
I created a branch called ```new_error``` containing all your commits w.r.t this issue.

Could you please use this branch in your development?

Thanks

**Comment by anjos** [comment]
As a rule of thumb, we should try to keep new/unfinished work on branches not to stop the advancement of the master branch with more mundane features.

**Comment by siebenkopf** [comment]
Yes, I agree. What do you think, should I add the branch to bob.nightlies, so that it is tested together with the other packages?
