### ISSUE TITLE
Test bob.measure.test_io.test_from_openbr fails on 64-bits Ubuntu Precise (LTS 12.04)

### ISSUE THREAD

**Issue by pkorshunov** [bioidiap/bob.measure#5]
The test fails due to the unsupported method numpy.isclose() from the numpy v1.6.1. Here is the error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/«PKGBUILDDIR»/build/lib.linux-x86_64-2.7/bob/measure/test_io.py", line 170, in test_from_openbr
    assert numpy.isclose(columns[i][-1], reference[i][-1], atol = 1e-3, rtol=1e-8), str(columns[i][-1]) + " != " + str(reference[i][-1])
AttributeError: 'module' object has no attribute 'isclose'

Here is the full buildlog that also reports the error:
https://launchpadlibrarian.net/229551648/buildlog_ubuntu-precise-amd64.bob.measure_2.0.5-0~ppa1~precise1_BUILDING.txt.gz

**Comment by tiagofrepereira2012** [comment]
According to this page https://github.com/idiap/bob/wiki/Dependencies, Bob is supposed to be compatible with Numpy >=1.3.

Numpy 1.6 is from 2011.
I think we can raise this requirement to numpy 1.7 (when the method ```isclose``` started to be supported - http://students.mimuw.edu.pl/~pbechler/numpy_doc/reference/generated/numpy.isclose.html)

Can I do this @anjos @siebenkopf  ?

Thanks

**Comment by anjos** [comment]
The implication of this is that we drop support for Ubuntu 12.04 LTS (see http://packages.ubuntu.com/search?keywords=python-numpy).

The minimum version to be supported should be 1.6.

**Comment by siebenkopf** [comment]
I agree. I guess that I can update the test to use another function, such as ``numpy.allclose()`` (which seems to be working in other packages, so I guess it is supported by Numpy 1.6)
